openapi: 3.0.0
paths:
  /v1/prescription:
    post:
      operationId: add-prescription
      summary: Add Prescriptions
      description: Add Prescriptions
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateprescriptionsDto"
      responses:
        "201":
          description: Prescription added successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PrescriptionSavedto"
      tags: &a1
        - Neblar Prescriptions API
  /v1/prescriptions/{nhi}:
    get:
      operationId: search-prescription
      summary: Search NHI
      description: Search NHI
      parameters:
        - name: nhi
          required: true
          in: path
          schema:
            type: string
      responses:
        "201":
          description: Filter prescriptions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CreateprescriptionsDto"
      tags: *a1
  /v1/prescription/{nhi}/{id}:
    put:
      operationId: update-prescription
      summary: Update Prescriptions
      description: Update Prescriptions
      parameters:
        - name: nhi
          required: true
          in: path
          schema:
            type: string
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePrescriptionDto"
      responses:
        "201":
          description: Update Prescription successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PrescriptionUpdateDto"
      tags: *a1
info:
  title: Neblar API Documentation
  description: >2-
     # Introduction
    This API is documented in OpenAPI format. It was extended to illustrate features of generator-openapi-repo tool and ReDoc documentation.

    '
      and standard method from web, mobile and desktop applications.
    <SecurityDefinitions />
  version: "1.0"
  contact:
    name: FHIR
    email: neblar.support@gmail.com
  license: {}
tags: []
servers:
  - url: http://localhost:1001/api
    description: ""
    variables: {}
components:
  schemas:
    PatientParam:
      type: object
      properties: {}
    CreateprescriptionsDto:
      type: object
      properties:
        patient:
          example: &a2
            nhi: nhi-1234
            name: Smith
          allOf:
            - $ref: "#/components/schemas/PatientParam"
        date:
          format: date-time
          type: string
          example: &a3 2024-01-09T10:47:49.104Z
        medications:
          example: &a4
            - id: 63afe809158d860c20c94aae
              dosage: 5ml
          type: array
          items:
            type: object
      required:
        - patient
        - date
        - medications
    PrescriptionSave:
      type: object
      properties:
        id:
          type: string
          example: 63afe809158d860c20c94aae
        message:
          type: string
          example: Prescription created successfully
      required:
        - id
        - message
    PrescriptionSavedto:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/PrescriptionSave"
    UpdatePrescriptionDto:
      type: object
      properties:
        patient:
          example: *a2
          allOf:
            - $ref: "#/components/schemas/PatientParam"
        date:
          format: date-time
          type: string
          example: *a3
        medications:
          example: *a4
          type: array
          items:
            type: object
    PrescriptionUpdateDto:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/PrescriptionSave"
externalDocs:
  url: http://localhost:1001/api
